version: '3'

services:
  frontend-web:
    build: ./frontend-app/Dockerfile
    container_name: 'frontend'
    ports:
      - '5000:5000'
  worker-backend:
    build: ./backend/Dockerfile
    container_name: 'worker-chek-backend'
    ports:
      - '0:0'
  db:
    build: ./db/Dockerfile
    container_name: 'db'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB_HOST=db
      - POSTGRES_DB_PORT=5432
    ports:
      - '5432:5432'
    volumes:
      - './db:/var/lib/postgresql/data'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'phpmyadmin'
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 5432
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - '8080:80'
    volumes:
      - './db:/var/lib/postgresql/data'